# Generated by Django 6.0.6 on 2026-06-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('tipo_pessoa', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], default='F', max_length=1)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('telefone', models.CharField(max_length=15)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('agencia', models.CharField(max_length=6)),
                ('tipo_conta', models.CharField(choices=[('CC', 'Conta Corrente'), ('CP', 'Conta Poupança'), ('CI', 'Conta Investimento')], default='CC', max_length=2)),
                ('saldo', models.DecimalField(decimal_places=2, default='0.00', max_digits=15)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='financeiro.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'Depósito'), ('S', 'Saque'), ('T', 'Transferência'), ('P', 'Pagamento')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('data_transacao', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transacoes', to='financeiro.conta')),
            ],
        ),
    ]
